config/routes.rb
Elections::Application.routes.draw do
  resources :candidates

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessible :area, :election_date, :email, :homepage, :mailing_address, :name, :office, :party, :phone, :latitude, :longitude, :gmaps
  acts_as_gmappable :address => "mailing_address", :lat => "latitude", :lng => "longitude", :process_geocoding => :geocode?

  #from  http://github.com/apneadiving/Google-Maps-for-Rails/wiki/DRY-example
  
  def geocode?
    (!mailing_address.blank? && (latitude.blank? || longitude.blank?)) || mailing_address_changed?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
    @json = Candidate.all.to_gmaps4rails do |candidate, marker|
	marker.infowindow "<strong><a href =\"/candidates/#{candidate.id}\">#{candidate.name}</a></strong><br>
        <strong>Party: </strong>#{candidate.party} <br>
        <strong>Office: </strong>#{candidate.office} <br> 
        <strong>Election Date: </strong>#{candidate.election_date} "
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party %><br />
    <%= f.text_field :party %>
  </div>
  <div class="field">
    <%= f.label :election_date %><br />
    <%= f.text_field :election_date %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :office %><br />
    <%= f.text_field :office %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>
  <div class="field">
    <%= f.label :mailing_address %><br />
    <%= f.text_field :mailing_address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br />
    <%= f.text_field :gmaps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Party</th>
    <th>Election date</th>
    <th>Area</th>
    <th>Office</th>
    <th>Homepage</th>
    <th>Mailing address</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @candidates.each do |candidate| %>
  <tr>
    <td><%= candidate.name %></td>
    <td><%= candidate.party %></td>
    <td><%= candidate.election_date %></td>
    <td><%= candidate.area %></td>
    <td><%= candidate.office %></td>
    <td><%= candidate.homepage %></td>
    <td><%= candidate.mailing_address %></td>
    <td><%= candidate.email %></td>
    <td><%= candidate.phone %></td>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
    <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>

<p>
  <b>Party:</b>
  <%= @candidate.party %>
</p>

<p>
  <b>Election date:</b>
  <%= @candidate.election_date %>
</p>

<p>
  <b>Area:</b>
  <%= @candidate.area %>
</p>

<p>
  <b>Office:</b>
  <%= @candidate.office %>
</p>

<p>
  <b>Homepage:</b>
  <%= @candidate.homepage %>
</p>

<p>
  <b>Mailing address:</b>
  <%= @candidate.mailing_address %>
</p>

<p>
  <b>Phone:</b>
  <%= @candidate.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @candidate.email %>
</p>


<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elections</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    'gmaps4rails' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= yield %>
<%= gmaps("markers" => { "data" => @json }) %>
<%= yield :scripts %>

</body>
</html>